#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Variables for the Synpred code
conda activate tf
tensorflow version 1.15
"""

__author__ = "A.J. Preto"
__email__ = "martinsgomes.jose@gmail.com"
__group__ = "Data-Driven Molecular Design"
__group_leader__ = "Irina S. Moreira"
__project__ = "SynPred"

"""
Global variables
"""
CSV_SEP = ","
SECONDARY_CSV_SEP = ";"
PARAGRAPH_SEP = "\n"
SYSTEM_SEP = "/"
INTERMEDIATE_SEP = "_"
TAB_SEP = "\t"
CSV_TERMINATION = ".csv"
SDF_TERMINATION = ".sdf"
PKL_TERMINATION = ".pkl"
SMILE_TERMINATION = ".smile"
DEFAULT_LOCATION = "/storage/pfilipe/synergy_2/DEC_deployment"
DATASET_FOLDER =  DEFAULT_LOCATION + SYSTEM_SEP + "datasets"
CCLE_FOLDER = DEFAULT_LOCATION + SYSTEM_SEP + "CCLE"
SUPPORT_FOLDER = DEFAULT_LOCATION + SYSTEM_SEP + "support"
MOLECULES_FOLDER = DEFAULT_LOCATION + SYSTEM_SEP + "molecules"
REDEPLOYMENT_FOLDER = DEFAULT_LOCATION + SYSTEM_SEP + "redeployment_variables"
DL_SAVED_MODELS = DEFAULT_LOCATION + SYSTEM_SEP + "saved_model"
EVALUATION_NON_DL_FOLDER = DEFAULT_LOCATION + SYSTEM_SEP + "evaluation_non_DL"
EVALUATION_DL_FOLDER = DEFAULT_LOCATION + SYSTEM_SEP + "evaluation_summary"
EVALUATION_DL_INDEX = "gridsearch_index" + CSV_TERMINATION
EVALUATION_DL_CUSTOM_INDEX = "gridsearch_index_custom" + CSV_TERMINATION

"""
NCI-ALMANAC variables
"""
NCI_ALMANAC_DATASET = DATASET_FOLDER + SYSTEM_SEP + "NCI_ALMANAC" + CSV_TERMINATION
CUSTOM_MOLECULES_FEATURES = DATASET_FOLDER + SYSTEM_SEP + "custom_molecules_features" + CSV_TERMINATION
NCI_ALMANAC_CELL_COLUMN = "CELLNAME"
CLASS_TRAIN_DATASET = DATASET_FOLDER + SYSTEM_SEP + "train_classes" + CSV_TERMINATION
CLASS_TEST_DATASET = DATASET_FOLDER + SYSTEM_SEP + "test_classes" + CSV_TERMINATION 
TRAIN_DATASET = DATASET_FOLDER + SYSTEM_SEP + "train" + CSV_TERMINATION
TEST_DATASET = DATASET_FOLDER + SYSTEM_SEP + "test" + CSV_TERMINATION

TRAIN_DATASET_PROCESSED = DATASET_FOLDER + SYSTEM_SEP + "train_processed" + CSV_TERMINATION
TEST_DATASET_PROCESSED = DATASET_FOLDER + SYSTEM_SEP + "test_processed" + CSV_TERMINATION

TRAIN_DATASET_ONE_HOT_CELL = DATASET_FOLDER + SYSTEM_SEP + "train_processed_one_hot_cell" + CSV_TERMINATION
TEST_DATASET_ONE_HOT_CELL = DATASET_FOLDER + SYSTEM_SEP + "test_processed_one_hot_cell" + CSV_TERMINATION

TRAIN_DATASET_NO_DRUG = DATASET_FOLDER + SYSTEM_SEP + "train_processed_no_drug_cell" + CSV_TERMINATION
TEST_DATASET_NO_DRUG = DATASET_FOLDER + SYSTEM_SEP + "test_processed_no_drug_cell" + CSV_TERMINATION

TRAIN_DATASET_CUSTOM_DRUG = DATASET_FOLDER + SYSTEM_SEP + "train_processed_custom_drug" + CSV_TERMINATION
TEST_DATASET_CUSTOM_DRUG = DATASET_FOLDER + SYSTEM_SEP + "test_processed_custom_drug" + CSV_TERMINATION

TRAIN_DATASET_RAW = DATASET_FOLDER + SYSTEM_SEP + "train_raw" + CSV_TERMINATION
TEST_DATASET_RAW = DATASET_FOLDER + SYSTEM_SEP + "test_raw" + CSV_TERMINATION

TRAIN_DATASET_PCA = DATASET_FOLDER + SYSTEM_SEP + "train_PCA" + CSV_TERMINATION
TEST_DATASET_PCA = DATASET_FOLDER + SYSTEM_SEP + "test_PCA" + CSV_TERMINATION

TRAIN_DATASET_PCA_DROP = DATASET_FOLDER + SYSTEM_SEP + "train_PCA_drop" + CSV_TERMINATION
TEST_DATASET_PCA_DROP = DATASET_FOLDER + SYSTEM_SEP + "test_PCA_drop" + CSV_TERMINATION

TRAIN_DATASET_AUTOENCODER = DATASET_FOLDER + SYSTEM_SEP + "train_autoencoder" + CSV_TERMINATION
TEST_DATASET_AUTOENCODER = DATASET_FOLDER + SYSTEM_SEP + "test_autoencoder" + CSV_TERMINATION

TRAIN_DATASET_AUTOENCODER_DROP = DATASET_FOLDER + SYSTEM_SEP + "train_autoencoder_drop" + CSV_TERMINATION
TEST_DATASET_AUTOENCODER_DROP = DATASET_FOLDER + SYSTEM_SEP + "test_autoencoder_drop" + CSV_TERMINATION

TRAIN_DATASET_PCA_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "train_PCA_custom_drugs" + CSV_TERMINATION
TEST_DATASET_PCA_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "test_PCA_custom_drugs" + CSV_TERMINATION

TRAIN_DATASET_PCA_DROP_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "train_PCA_drop_custom_drugs" + CSV_TERMINATION
TEST_DATASET_PCA_DROP_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "test_PCA_drop_custom_drugs" + CSV_TERMINATION

TRAIN_DATASET_AUTOENCODER_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "train_autoencoder_custom_drugs" + CSV_TERMINATION
TEST_DATASET_AUTOENCODER_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "test_autoencoder_custom_drugs" + CSV_TERMINATION

TRAIN_DATASET_AUTOENCODER_DROP_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "train_autoencoder_drop_custom_drugs" + CSV_TERMINATION
TEST_DATASET_AUTOENCODER_DROP_CUSTOM_DRUGS = DATASET_FOLDER + SYSTEM_SEP + "test_autoencoder_drop_custom_drugs" + CSV_TERMINATION

COLUMN_CLASSES = ["ZIP","Bliss","HSA"]
FULL_AGREEMENT_COLUMN_NAME = "Full-agreement"

SCALER_MORDRED_FILE = "scaler_mordred.pkl"
SCALER_MORDRED_FILE_ONE_HOT = "scaler_mordred_one_hot.pkl"
SCALER_CUSTOM_FILE = "scaler_custom.pkl"

"""
h5 datasets
"""
H5_DATASET_RAW = DATASET_FOLDER + SYSTEM_SEP + "dataset_raw.h5"

"""
CCLE variables
"""
SCALED_CCLE_START = "scaler_CCLE_subset"
CCLE_ID_COLUMN_NAME = "ID"
CCLE_ID_COLUMN_SEP = "&"
CCLE_ANNOTATION_FILE = CCLE_FOLDER + SYSTEM_SEP + "Cell_line_annotations.txt"
SUBSET_CCLE = "CCLE_subset" + CSV_TERMINATION
FILTERED_CCLE = "CCLE_filtered" + CSV_TERMINATION
PCA_CCLE = "CCLE_PCA" + CSV_TERMINATION
TSNE_CCLE = "CCLE_tsne" + CSV_TERMINATION
AUTOENCODER_CCLE = "CCLE_autoencoder" + CSV_TERMINATION
CCLE_COLUMN_TAG = "CCLE"

"""
Support variables
"""
CCLE_DATASET_LOG_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "CCLE_log_file.csv"
CCLE_COLUMNS_KEPT_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "columns_kept_names.csv"
FEATURES_IMPORTANCE_OUTPUT_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "feature_importance.csv"
TSNE_PLOT_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "tsne_plot.png"
TSNE_TABLE_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "tsne_table.csv"
PCA_PLOT_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "PCA_plot.png"
PCA_TABLE_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "PCA_table.csv"
AUTOENCODER_LOG_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "autoencoder_scores.csv"
MORDRED_RAW_FILE = SUPPORT_FOLDER + SYSTEM_SEP + "mordred_features_clean.csv"
CORRECTION_DICTIONARY = {"CAKI-1":"Caki-1","NCI-H322M":"NCI-H322",
		"MDA-MB-231/ATCC":"MDA-MB-231","A498":"A-498","OVCAR-3":"NIH:OVCAR-3",
		"HS 578T":"Hs 578T","MDA-MB-435":"MDA-MB-435S","786-0":"786-O",
		"MALME-3M":"Malme-3M","HL-60(TB)":"HL-60","SW-620":"SW620",
		"HCT-116":"HCT 116","DU-145":"DU 145","A549/ATCC":"A549",
		"U251":"U-251 MG","RPMI-8226":"RPMI 8226","HT29":"HT-29",
		"SR":"SR-786","TK-10":"TK10","SF-268":"SF268",
		"SF-539":"SF539","SNB-75":"SNB75","HCC-2998":"HCC2998",
		"NCI/ADR-RES":"ADRRES","RXF 393":"RXF393","SN12C":"SN-12C",
		"CCRF-CEM":"CCRFCEM"}
DROPPABLE_COLUMNS = ['cell', 'drug1', 'drug2', 'ZIP', 'Bliss', 'HSA','Full-agreement']
TARGET_CLASS_COLUMN = ["Full-agreement"]
RANDOM_STATE = 42
METRICS_NAME_LIST = ["Accuracy","Precision","Recall","AUC","F1-score"]

